<?php


/**
*
*/
class PHPX
{

  ########################

  /**
  *
  */
  public function __construct($argument) {
    // code...
  }
  /**
  *
  */

  ########################



  #
  #
  #
  #
  #
  #



  ########################

  /**
  *
  */
  public static function VALIDATE_url($url) {
    // code...

    if (filter_var($url, FILTER_VALIDATE_URL)) {
      return true;
    } else {
      return false;
    }
  }
  /**
  *
  */

  ########################
  
  
  #
  #
  #
  #
  #
  #




}